_BASE_: "CLIFF_COCO_RCNN-C4.yaml"
OUTPUT_DIR: output/cliff/stage1
DDPM:
  NUM_DDPM_SETPS: 10
  NORM_DDPM_SAMPLING: 'clamp'
  NUM_BOTTLENECK_LAYERS: 2
  HIDDEN_DIM: 1024
  WITH_RECONSTRUCTION: True
  KL_LOSS_WEIGHT: 2.0
  LOSS_WEIGHT_REGION_TO_IMAGE: 15.0
  WITH_REGION_TO_IMAGE: False
  WITH_COND_NOISE: False
  WITH_OVER_SAMPLING: True
MODEL:
  # WEIGHTS: "/data/wyli/code/CLIFF/coco_ovd_base.pth"
  META_ARCHITECTURE: "CustomRCNNMViT"
  PIS_PROP_PATH: /data/wyli/data/coco/MAVL_proposals/coco_props/class_specific # change to your path
  ROI_BOX_HEAD:
    USE_DDPM: True
    WS_NUM_PROPS: 32
    IMAGE_LABEL_LOSS: 'pseudo_max_score'
SOLVER:
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 30000
DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder", "coco_caption_train_tags")
INPUT:
  CUSTOM_AUG: ResizeShortestEdge
  MIN_SIZE_TRAIN_SAMPLING: range
  MIN_SIZE_TRAIN: (800, 800)
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 4]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [4, 16] # Batch-size per GPU
  USE_RFS: [False, False]
  DATASET_MIN_SIZES: [[800, 800], [400, 400]]
  DATASET_MAX_SIZES: [1333, 667]
  FILTER_EMPTY_ANNOTATIONS: False
  MULTI_DATASET_GROUPING: True
  DATASET_ANN: ['box', 'image']
  NUM_WORKERS: 8
WITH_IMAGE_LABELS: True
TEST:
  EVAL_PERIOD: 30000
