DDPM:
  NUM_DDPM_SETPS: 10
  NORM_DDPM_SAMPLING: 'clamp'
  NUM_BOTTLENECK_LAYERS: 2
  HIDDEN_DIM: 1024
  WITH_RECONSTRUCTION: True
  WITH_REGION_TO_IMAGE: False
  LOSS_WEIGHT_REGION_TO_IMAGE: 1.0
  WITH_COND_NOISE: True
  NUM_STEPS_REGION_TO_IMAGE: 3
  NUM_STEPS_REGION_TO_TEXT: 10
MODEL:
  META_ARCHITECTURE: "CustomRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "CustomRes5ROIHeads"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    USE_DDPM: True
    CLS_AGNOSTIC_BBOX_REG: True
    USE_SIGMOID_CE: True
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_PATH: 'datasets/zeroshot_weights/coco_clip_a+photo+cname.npy'
    IGNORE_ZERO_CATS: True
    CAT_FREQ_PATH: '/data/wyli/data/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json' # change to your path
DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder",)
  TEST: ("coco_generalized_zeroshot_val",)
SOLVER:
  IMS_PER_BATCH: 16 # Overall batch-size
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 20000
INPUT:
  MIN_SIZE_TRAIN: (800,)
DATALOADER:
  NUM_WORKERS: 8
VERSION: 2
OUTPUT_DIR: output/cliff/stage1_detector
FP16: False
SEED: 0 
# TEST:
#   EVAL_PERIOD: 10000